"use client";

import { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import {
  IconCompliance,
  IconCRM,
  IconAI,
  IconAlerts,
  IconFinance,
  IconPeople,
  IconDocument,
  IconLedger,
} from "./components/Icons";
import { Reveal } from "./components/Reveal";
import { WhoItsFor } from "./components/WhoItsFor";
import { PricingCard, PricingToggle } from "./components/Pricing";
import { SocialProof } from "./components/SocialProof";
import { TrustBadge } from "./components/TrustBadge";
import { FAQ } from "./components/FAQ";
import { BlogHighlights } from "./components/BlogHighlights";
import { MarketingFooter } from "./components/MarketingFooter";
import { SiteNav } from "./components/SiteNav";
import { Hero } from "./components/Hero";
import { HeroVideo } from "./components/HeroVideo";
import { ProductDemo } from "./components/ProductDemo";

/* ═══════════════════════════ PAGE ═══════════════════════════════ */

interface Capability {
  icon: React.ReactNode;
  title: string;
  description: string;
  /** Bento span + optional real screenshot for feature cells. */
  span?: string;
  screenshot?: { src: string; alt: string };
}

/** Core capabilities — everything listed here is live in the product. */
const CAPABILITIES: Capability[] = [
  {
    icon: <IconAI />,
    title: "Customer health scoring",
    description:
      "Every account scored 0-100 on usage, payments, and support signals. You see who's drifting toward the exit while there's still time to call.",
    span: "md:col-span-2 md:row-span-2",
    screenshot: {
      src: "/screenshots/churn-alerts.png",
      alt: "Churn alert rules in the SaaSy product: trigger conditions for health score drops, failed payments, and inactivity.",
    },
  },
  {
    icon: <IconCRM />,
    title: "Built-in CRM & projects",
    description:
      "Contacts, deals, pipeline, quotes, and projects in one place, with nothing duct-taped between them.",
  },
  {
    icon: <IconFinance />,
    title: "Books that close themselves",
    description:
      "Financial statements, continuous close, and an AI CFO brief that reads your numbers weekly and ranks what to do about them.",
  },
  {
    icon: <IconCompliance />,
    title: "Compliance tracker",
    description:
      "Licenses, permits, filings, and payroll deadlines tracked automatically. Reminders land before the due date, not after the fine.",
  },
  {
    icon: <IconAlerts />,
    title: "Proactive alerts",
    description:
      "Email or Slack pings when something needs you: a churn risk, a deadline, a missed payment. The system watches so you don't have to.",
  },
  {
    icon: <IconLedger />,
    title: "Native payroll, 50 states + DC",
    description:
      "Direct deposit, W-2s, and WH-347 certified payroll for government work, built in, not bolted on.",
    span: "md:col-span-2",
    screenshot: {
      src: "/screenshots/wh347-certified-payroll.png",
      alt: "A WH-347 certified payroll report generated by SaaSy for a public-works contractor.",
    },
  },
  {
    icon: <IconPeople />,
    title: "Hiring & people",
    description:
      "Post a role, track candidates, send offers, and run onboarding, benefits, and reviews without a separate HR tool.",
  },
  {
    icon: <IconDocument />,
    title: "Documents & e-signature",
    description:
      "Draft contracts with an AI assistant, send for signature, and keep every version, plus grant discovery with AI-written proposals.",
  },
];

export default function Home(): React.ReactElement {
  const [pricingInterval, setPricingInterval] = useState<
    "monthly" | "annual"
  >("monthly");

  const monthlyPrices = { starter: 49, growth: 199, scale: 399 };
  const annualPrices = { starter: 39, growth: 159, scale: 319 };
  const prices =
    pricingInterval === "annual" ? annualPrices : monthlyPrices;
  const billingLabel =
    pricingInterval === "annual" ? "/mo billed annually" : "/mo";

  return (
    <div className="min-h-screen">
      {/* ─────────────── Navigation ─────────────── */}
      <SiteNav />

      {/* ─────────────────── Hero ─────────────────── */}
      <Hero />

      {/* ─────────────── Trust Strip ─────────────────── */}
      <section
        className="border-y border-saasy-border bg-saasy-card/30"
        aria-label="Security and data practices"
      >
        <div
          className="mx-auto grid max-w-5xl grid-cols-2 gap-y-6
            px-6 py-8 sm:grid-cols-4 sm:divide-x
            sm:divide-saasy-border"
        >
          <TrustBadge
            label="Encrypted"
            sublabel="At rest and in transit"
          />
          <TrustBadge
            label="Your data stays yours"
            sublabel="Strict per-account isolation"
          />
          <TrustBadge
            label="GDPR-ready"
            sublabel="Export or delete anytime"
          />
          <TrustBadge
            label="Real humans"
            sublabel="US-based support"
          />
        </div>
        <p className="pb-6 text-center text-sm text-saasy-muted">
          Not just badges:{" "}
          <Link
            href="/privacy"
            className="text-saasy-pink-soft underline
              transition-colors hover:text-white"
          >
            read exactly how we handle your data
          </Link>
          .
        </p>
      </section>

      {/* ─────────────── Features ─────────────────── */}
      <section id="features" className="py-24 sm:py-32">
        <div className="mx-auto max-w-6xl px-6">
          <Reveal>
            <div className="mb-14 max-w-2xl">
              <h2
                className="text-3xl font-bold tracking-tight text-white
                  sm:text-4xl"
              >
                Software that does the work
              </h2>
              <p className="mt-4 text-lg text-saasy-muted">
                Most tools hand you a chart of the problem and wish
                you luck. SaaSy&rsquo;s agents chase the deadline,
                score the customer, and draft the follow-up. Then
                they tell you what they did.
              </p>
            </div>
          </Reveal>

          {/* Product walkthrough video — the destination for the hero's
              "See how it works" CTA. */}
          <ProductDemo />

          {/* Capability bento: feature cells carry real product
              screenshots, the rest stay quiet. */}
          <div
            className="grid grid-flow-dense gap-5 md:grid-cols-2
              lg:grid-cols-4"
          >
            {CAPABILITIES.map((cap, i) => (
              <Reveal
                key={cap.title}
                index={i % 4}
                className={`${cap.span ?? ""} h-full`}
              >
                <div
                  className="group flex h-full flex-col rounded-2xl
                    border border-saasy-border bg-saasy-card/50 p-6
                    transition-colors hover:border-saasy-pink/30"
                >
                  {cap.screenshot && (
                    <div
                      className="mb-5 overflow-hidden rounded-lg border
                        border-saasy-border"
                    >
                      <Image
                        src={cap.screenshot.src}
                        alt={cap.screenshot.alt}
                        width={1195}
                        height={900}
                        className="h-auto w-full object-cover
                          transition-transform duration-500
                          group-hover:scale-[1.02]"
                      />
                    </div>
                  )}
                  <div className="mb-3">{cap.icon}</div>
                  <h3 className="text-lg font-semibold text-white">
                    {cap.title}
                  </h3>
                  <p
                    className="mt-2 text-sm leading-relaxed
                      text-saasy-muted"
                  >
                    {cap.description}
                  </p>
                </div>
              </Reveal>
            ))}
          </div>

          <div className="mt-12">
            <Link
              href="/features"
              className="text-sm font-medium text-saasy-pink-soft
                transition-colors hover:text-white"
            >
              See every feature in real screenshots &rarr;
            </Link>
            <p className="mt-3 max-w-md text-xs text-saasy-muted">
              The numbers in the demo aren&rsquo;t set dressing.{" "}
              <a
                href="/downloads/sample-customer-health.json"
                download
                className="underline transition-colors hover:text-white"
              >
                Download the raw health data behind these screens
              </a>{" "}
              and check them yourself.
            </p>
          </div>
        </div>

        {/* The journey loop closes the section and hands off to
            who-it's-for. */}
        <div className="mx-auto mt-20 max-w-6xl px-6">
          <HeroVideo />
        </div>
      </section>

      {/* ─────────────── Who It's For ─────────────── */}
      <WhoItsFor />

      {/* ─────────────── Beta Social Proof ─────────── */}
      <SocialProof />

      {/* ─────────────── Pricing ─────────────────── */}
      <section
        id="pricing"
        className="border-t border-saasy-border py-24 sm:py-32"
      >
        <div className="mx-auto max-w-6xl px-6">
          <Reveal>
            <div className="mx-auto mb-10 max-w-2xl text-center">
              <h2
                className="text-3xl font-bold tracking-tight text-white
                  sm:text-4xl"
              >
                Simple, transparent pricing
              </h2>
              <p className="mt-4 text-lg text-saasy-muted">
                Every trial starts with full Growth access, free for
                14 days. No credit card up front.
              </p>
            </div>
          </Reveal>

          <div className="mb-12 flex justify-center">
            <PricingToggle
              interval={pricingInterval}
              onChange={setPricingInterval}
            />
          </div>

          <div
            className="mx-auto grid max-w-5xl items-stretch gap-8
              lg:grid-cols-3"
          >
            <PricingCard
              name="Starter"
              price={prices.starter}
              billingLabel={billingLabel}
              features={[
                "1 business",
                "3 team seats",
                "Compliance tracker",
                "CRM (1,000 contacts)",
                "Daily briefing",
                "Email alerts",
              ]}
            />
            <PricingCard
              name="Growth"
              price={prices.growth}
              popular
              billingLabel={billingLabel}
              features={[
                "Everything in Starter",
                "Up to 5 businesses",
                "10 team seats",
                "CRM (10,000 contacts)",
                "Native payroll, 50 states + DC (beta perk)",
                "Ask SaaSy AI guidance",
                "Slack alerts",
                "API access",
              ]}
            />
            <PricingCard
              name="Scale"
              price={prices.scale}
              billingLabel={billingLabel}
              features={[
                "Everything in Growth",
                "Unlimited businesses",
                "Advanced analytics",
                "Priority support",
                "Custom automations",
                "Dedicated onboarding",
              ]}
            />
          </div>

          <div className="mt-12 text-center">
            <Link
              href="/compare"
              className="text-sm font-medium text-saasy-pink-soft
                transition-colors hover:text-white"
            >
              See how SaaSy compares to the tools it replaces &rarr;
            </Link>
            <p className="mx-auto mt-4 max-w-xl text-sm text-saasy-muted">
              Need custom automations, integrations, or a dedicated
              engineering partner?{" "}
              <a
                href="https://saasysolutionsllc.com/consultation"
                className="font-medium text-saasy-orange
                  transition-colors hover:text-white"
              >
                Talk to our consulting team &rarr;
              </a>
            </p>
          </div>
        </div>
      </section>

      {/* ─────────────── FAQ ─────────────────────── */}
      <FAQ />

      {/* ─────────────── Blog Highlights ─────────── */}
      <BlogHighlights />

      {/* ───────────── Final CTA ──────────────────── */}
      <section className="border-t border-saasy-border">
        <Reveal>
          <div
            className="hero-gradient mx-auto max-w-4xl px-6
              py-24 text-center sm:py-32"
          >
            <h2
              className="text-3xl font-bold tracking-tight text-white
                sm:text-5xl"
            >
              Ready to run your business smarter?
            </h2>
            <p
              className="mx-auto mt-4 max-w-xl text-lg
                text-saasy-muted"
            >
              We&rsquo;re in open beta, building alongside our first
              customers. Your feedback ships in days, and your first
              two weeks are free.
            </p>
            <Link
              href="https://app.hellosaasy.ai/signup"
              className="mt-8 inline-flex rounded-full
                bg-saasy-rose px-8 py-4 text-base
                font-semibold text-white
                transition-all hover:bg-saasy-rose-bright
                active:translate-y-[1px]"
            >
              Start your free trial
            </Link>
            <p className="mt-4 text-sm text-saasy-muted">
              Want a walkthrough first?{" "}
              <a
                href="https://app.hellosaasy.ai/contact-sales"
                data-cta="home"
                className="font-medium text-saasy-pink-soft
                  transition-colors hover:text-white"
              >
                Talk to sales
              </a>
            </p>
          </div>
        </Reveal>
      </section>

      {/* ─────────────── Footer ─────────────────── */}
      <MarketingFooter />
    </div>
  );
}
